### ISSUE TITLE
todo:

### ISSUE THREAD

**Issue by mizlan** [mizlan/mzchael.com#1]
- [ ] talk about how color-matching the signature via CSS `filter:` was achieved
- [x] use warmer color for purple
- [x] fix mb for this-site
- [x] use radix-ui
- [x] remove dependency on Typography [In progress]
- [ ] make width transitions seamless
- [ ] Use currentColor for svg CANT FIX
- [ ] Use CSS mask for signature
- [ ] focus for nav link after element color change
